apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "Nephelite.fullname" . }}-appsettings
  labels:
    {{- include "Nephelite.labels" . | nindent 4 }}
data:
  appsettings.json: |
    {
      "Logging": {
        "LogLevel": {
          "Default": "Information",
          "Microsoft.AspNetCore": "Warning"
        }
      },
      "AllowedHosts": "*",
      "Fido2Config": {
        "serverDomain": "{{ .Values.nephelite.host }}",
        "serverName": "{{ .Values.nephelite.host }}",
        "origins": [ "https://{{ .Values.nephelite.host }}" ],
        "timestampDriftTolerance": 300000
      },
      "Nephelite": {
        "Host": "{{ .Values.nephelite.host }}"
      }
    }
