---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: users.nephelite.norelect.ch
spec:
  group: nephelite.norelect.ch
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                username:
                  type: string
                email:
                  type: string
                groups:
                  type: array
                  items:
                    type: string
                credentials:
                  type: array
                  items:
                    type: object
                    properties:
                      credentialId:
                        type: string
                      publicKey:
                        type: string
            status:
              type: object
              properties:
                signatureCounters:
                  type: object
                  x-kubernetes-preserve-unknown-fields: true
                lastAuthentication:
                  type: string
      subresources:
        status: {}
      additionalPrinterColumns:
        - name: Username
          type: string
          jsonPath: .spec.username
        - name: Email
          type: string
          jsonPath: .spec.email
        - name: Last Login
          type: string
          jsonPath: .status.lastAuthentication
  scope: Namespaced
  names:
    plural: users
    singular: user
    kind: User
---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: clients.nephelite.norelect.ch
spec:
  group: nephelite.norelect.ch
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                clientId:
                  type: string
                clientSecret:
                  type: string
                redirectUris:
                  type: array
                  items:
                    type: string
                confidential:
                  type: boolean
                tokenLifetime:
                  type: string
  scope: Namespaced
  names:
    plural: clients
    singular: client
    kind: Client
